language: c

compiler: gcc

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

before_"Tests":
  - sudo add-apt-repository ppa:snaipewastaken/ppa < test.cmd
  - sudo apt-get update
  - sudo apt install gcovr < test.cmd
  - sudo apt-get install criterion-dev < test.cmd

jobs:
  include:
    - stage: "Build"
      script: make
    - stage: "Compilation"
      script:
        - make
        - ./bsq mouli_maps/testing_map
    - stage: "Tests"
      script: make tests_run