language: c

compiler: gcc

before_build:
  - git clone --recursive https://github.com/Snaipe/Criterion
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

script: make && ./bsq mouli_maps/testing_map