language: c

services:
  - docker

notifications:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

env:
  global:
    - DOCKER_REPO=cyberryteam/epitech-docker:fedora

install:
  - docker pull ${DOCKER_REPO}

jobs:
  include:
    - stage: Build
      name: "Building"
      script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && make"
    - stage: Tests
      name: "Basic Tests"
      script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && ./tests/basic_tests.sh bsq"
    - script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && make tests_run"
      name: "Make the tests"
    - stage: Deployment
      name: "Push to blih repo"
      script:
        - ssh-keyscan -H git.epitech.eu >> ~/.ssh/known_hosts
        - git remote add blih git@git.epitech.eu:/tomas.forne-cappeau@epitech.eu/CPE_BSQ_2018

stages:
  - Build
  - Tests
  - name: Deployment
    if: branch = master