language: c

services:
  - docker

before_install:
  - docker pull epitechcontent/epitest-docker:latest
  - docker run -d -p 127.0.0.1:80:4567 epitechcontent/epitest-docker:latest
  - docker ps -a
  - docker run epitechcontent/epitest-docker:latest

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: "Build"
      script: make
    - stage: "Compilation"
      script:
        - make
        - ./bsq mouli_maps/testing_map
    - stage: "Tests"
      script: make tests_run