language: c

services:
  - docker

before_install:
  - docker pull epitechcontent/epitest-docker:latest
  - docker run -d -p 127.0.0.1:80:4567 epitechcontent/epitest-docker:latest
  - docker ps -a

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: "Build"
      name: "Building"
      script: make
      - script: ./bsq mouli_maps/testing_map
      name: "Compilation"
    - stage: "Tests"
      name: "Basic tests"
      script: ./basic_tests.sh basic_tests.sh
      - script: make tests_run
      name: "Criterion tests"
