language: c

compiler: gcc

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa < test.cmd
  - sudo apt-get update
  - sudo apt install gcovr < test.cmd
  - sudo apt-get install criterion-dev < test.cmd

build:
  script:
    - make

test:
  script:
    - ./bsq mouli_maps/testing_map
    - make tests_run
