language: c

compiler: gcc

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

script:
  - sudo add-apt-repository ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get install criterion-dev
  - make
  - ./bsq mouli_maps/testing_map
  - make tests_run