language: c

services:
  - docker

script:
  - docker pull epitechcontent/epitest-docker:latest

before_install:
  - docker run -i -t epitechcontent/epitest-docker:latest
  - docker ps -a

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
      - tomasforne1@gmail.com
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: "Build"
      script: make
    - stage: "Compilation"
      script:
        - make
        - ./bsq mouli_maps/testing_map
    - stage: "Tests"
      script: make tests_run
