language: c

compiler: gcc

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
    on_success: never
    on_failure: always

before_build:
  - sudo add-apt-repository ppa:snaipewastaken/ppa < test.cmd
  - sudo apt-get update
  - sudo apt-get install criterion-dev < test.cmd
  - sudo apt install gcovr < test.cmd

stages:
  - name: build
    script:
      - make

script:
  - ./bsq mouli_maps/testing_map
  - make tests_run

deploy:
  - echo "Hello"